"""Add mind_map column

Revision ID: 9394312cab17
Revises: 
Create Date: 2025-05-16 11:27:47.188266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9394312cab17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mind_map', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_files', schema=None) as batch_op:
        batch_op.drop_column('mind_map')

    # ### end Alembic commands ###
